services:
    custom-rpi-image:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-omeka:latest
        volumes:
            - ./custom-rpi-image:/home/imagegen/custom-rpi-image